{{- if .Values.rbac.extraPermissions.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.extraPermissions.serviceAccountName }}
subjects:
  - kind: ServiceAccount
    name:  {{ .Values.rbac.extraPermissions.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.extraPermissions.serviceAccountName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
