{{- if .Values.rbac.extraPermissions.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.extraPermissions.roleBindingName }}
subjects:
  - kind: ServiceAccount
    name:  {{ index .Values "spark-operator" "serviceAccounts" "spark" "name" }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.extraPermissions.roleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
