apiVersion: v2
name: platform-spark
description: A Helm chart to deploy Spark cluster app
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: spark-operator
    version: "1.1.27"
    repository: https://googlecloudplatform.github.io/spark-on-k8s-operator
    condition: spark-operator.enabled
